load("@rules_java//java:defs.bzl", "java_library")

package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "junit",
    exports = ["@external_deps//:junit_junit"],
)

java_library(
    name = "hamcrest",
    exports = ["@external_deps//:org_hamcrest_hamcrest"],
)
