load("@rules_java//java:defs.bzl", "java_library")

package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "junit",
    exports = ["@junit//jar"],
)

java_library(
    name = "hamcrest",
    exports = ["@hamcrest//jar"],
)
