maven_jar(
  name = 'soy',
  id = 'com.google.template:soy:2016-01-12',
  sha1 = 'adadc37aecf1042de7c9c6a6eb8f34719500ed69',
  deps = [
    ':icu4j',
    '//lib:jsr305',
  ],
)

maven_jar(
  name = 'icu4j',
  id = 'com.ibm.icu:icu4j:51.1',
  sha1 = '8ce396c4aed83c0c3de9158dc72c834fd283d5a4',
)
