load("//lib:provided.bzl", "provided_java_library")

provided_java_library(
    name = "flogger",
    exports = [
        "@external_deps//:ch_qos_reload4j_reload4j",
        "@external_deps//:com_google_flogger_flogger",
        "@external_deps//:com_google_flogger_flogger_log4j_backend",
        "@external_deps//:com_google_flogger_flogger_system_backend",
        "@external_deps//:com_google_flogger_google_extensions",
    ],
)
