load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "flogger",
    visibility = ["//visibility:public"],
    exports = [
        "@flogger-google-extensions//jar",
        "@flogger-log4j-backend//jar",
        "@flogger-system-backend//jar",
        "@flogger//jar",
        "@log4j//jar",
    ],
)
