java_library(
  name = 'dev',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    '//gitiles-servlet:servlet',
    '//lib:guava',
    '//lib/jgit:jgit',
    '//lib/jgit:jgit-servlet',
    '//lib/jetty:server',
    '//lib/jetty:servlet',
    '//lib:log-api',
    '//lib:servlet-api-3_1',
    '//lib:soy',
  ],
  visibility = ['PUBLIC'],
)
