# Bazlets dependency pin kept outside the root module declaration.
bazel_dep(name = "com_googlesource_gerrit_bazlets")
git_override(
    module_name = "com_googlesource_gerrit_bazlets",
    commit = "6238d6cc469d0bb0f18d97669320d2a900465181",
    remote = "https://gerrit.googlesource.com/bazlets",
)
