# Bazlets dependency pin kept outside the root module declaration.
bazel_dep(name = "com_googlesource_gerrit_bazlets")
git_override(
    module_name = "com_googlesource_gerrit_bazlets",
    commit = "b13c81265c40ba9283eb1a9f7292ec35b94ba47d",
    remote = "https://gerrit.googlesource.com/bazlets",
)
