# Bazlets dependency pin kept outside the root module declaration.
bazel_dep(name = "com_googlesource_gerrit_bazlets")
git_override(
    module_name = "com_googlesource_gerrit_bazlets",
    commit = "cdd07f02ee0dc585ae2a310061d33662e5d098b6",
    remote = "https://gerrit.googlesource.com/bazlets",
)
